mqtt:
  enabled: false

go2rtc:
  streams:
    doorbell:
      - "rtsp://{FRIGATE_VIVINT_RTSP_USER}:{FRIGATE_VIVINT_RTSP_PASS}@192.168.51.106:8554/Video-188"
    nest_cam_1:
      - "nest:///enterprises/{FRIGATE_NEST_PROJECT_ID}/devices/{FRIGATE_NEST_CAM1_DEVICE_ID}?client_id={FRIGATE_NEST_CLIENT_ID}&client_secret={FRIGATE_NEST_CLIENT_SECRET}&refresh_token={FRIGATE_NEST_REFRESH_TOKEN}"
    nest_cam_2:
      - "nest:///enterprises/{FRIGATE_NEST_PROJECT_ID}/devices/{FRIGATE_NEST_CAM2_DEVICE_ID}?client_id={FRIGATE_NEST_CLIENT_ID}&client_secret={FRIGATE_NEST_CLIENT_SECRET}&refresh_token={FRIGATE_NEST_REFRESH_TOKEN}"
    nanit_benjamin:
      - "rtmp://192.168.51.179:1935/local/{FRIGATE_NANIT_BENJAMIN_UID}"
    nanit_travel:
      - "rtmp://192.168.51.179:1935/local/{FRIGATE_NANIT_TRAVEL_UID}"

detectors:
  cpu:
    type: cpu
    num_threads: 3

detect:
  enabled: true
  width: 640
  height: 480
  fps: 5

objects:
  track:
    - person
  filters:
    person:
      min_score: 0.5
      threshold: 0.7

record:
  enabled: false

snapshots:
  enabled: true
  retain:
    default: 7

cameras:
  doorbell:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5

  nest_cam_1:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nest_cam_1
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5

  nest_cam_2:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nest_cam_2
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5

  nanit_benjamin:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nanit_benjamin
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5

  nanit_travel:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/nanit_travel
          roles:
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
